config/routes.rb
Rails.application.routes.draw do
  root 'maps#home'
  resources :proofs, only: [:create, :destroy]
  resources :packages, only: [:create, :destroy]
  resources :ulocs, only: [:create, :update, :destroy]
  

end

app/models/package.rb
class Package < ActiveRecord::Base
	validates :address, presence: true
	before_create {
		coords = Geocoder.coordinates self.address
		self.longitude = coords[0]
		self.latitude = coords[1]
	}
end

app/models/proof.rb
class Proof < ActiveRecord::Base
	
	validates_presence_of :picture, message: "Please select a JPEG file" 
	validates_presence_of :longitude, message: "was not found in your file." 
	validates_presence_of :latitude, message: "was not found in your file." 
	validates_presence_of :taken_at, message: "was not found in your file." 
	validates_uniqueness_of [:longitude, :latitude, :taken_at]
	mount_uploader :picture, PictureUploader
	before_validation :geolocate

	def geolocate 	
		p = EXIFR::JPEG.new(picture.path)		
		self.longitude = p.gps.longitude if !p.gps.nil?
		self.latitude =  p.gps.latitude	if !p.gps.nil?
		self.taken_at = p.date_time_original if !p.date_time_original.nil?
	
	end
end

app/models/route.rb
class Route < ActiveRecord::Base
	serialize :order
	validates :order, presence: true, uniqueness: true 
	#order unique
end

app/models/uloc.rb
class Uloc < ActiveRecord::Base
	validates :longitude, presence: true
	validates :latitude, presence: true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def optimized_order #calls Mapquest API to order input to minimize travel time

  if Package.count > 1 
      group = []
      anchor = Package.last.created_at
      lim = 5.seconds
       
      min = anchor - lim
      max =  anchor + lim 

      Package.where(created_at: min..max).each {|package| group << "#{package.address}"} 

      optimized_order = []
      Route.all.each do |route|
        optimized_order = route.order if route.order.sort == group.sort #search for match
      end

      optimized_locations = []

      if optimized_order != [] #route already calculated
        optimized_order.each do |loc|
          p = Package.where(address: loc).last
          optimized_locations << [p.address, p.latitude, p.longitude]
        end



      else #call mapquest api to calculate new route

      url = URI("http://www.mapquestapi.com/directions/v2/optimizedroute?key=sXUK5TTzyRju00qjsZ755oUZLCfB7LFS")
    	http = Net::HTTP.new(url.host, url.port)
    	request = Net::HTTP::Post.new(url)
    	request["cache-control"] = 'no-cache'
    	request["content-type"] = 'text/json'
    	request.body = "{locations: #{group} }"
    	response = http.request(request)

    	#handle response
    	response = JSON.parse(response.body)
    	optimized_order = response["route"]["locationSequence"]

      optimized_order.each do |index|
        p = Package.where(address: group[index]).last
        optimized_locations << [p.address, p.latitude, p.longitude]

        new_route = []
        optimized_locations.each {|loc| new_route << loc[0]} #address
       Route.create(order: new_route ) #save new route
        
    end

  end
  	return optimized_locations

  else 
    optimized_locations = []

  end

  end

end
 #group << startpoint

    #locations = [
#        '{ latLng: {lat: 39.637433, lng: -105.163867 }}',
#        '{ latLng: {lat: 39.743943, lng: -105.020089 }}'
#      ]

app/controllers/maps_controller.rb
class MapsController < ApplicationController
		def home
			@proof = Proof.new#(proof_params)
			@route = []
			5.times do 
				@route << Package.new
			end

			gon.exif = []
			Proof.all.each { |p| gon.exif << [p.latitude, p.longitude, p.taken_at, p.picture.url] }

			@oo = optimized_order
			@group = []
				
			@map_route = []
			optimized_order.each {|coords| @map_route << [coords[2], coords[1]]} #[gon.route << address, lat, long]
			@uloc = Uloc.new
		end



	private 
		def proof_params
		#	params.require(:proof).permit(:picture)
		end

end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

	def new 
		@route = []
		5.times do 
			@route << Package.new
		end
	end

		def create
			params["packages"].each do |package|
				if package["address"] != "" #does not add empty form fields
					@pack = Package.create(package_params(package))					
				end
		end			

      	redirect_to root_url
	end

	private
	def package_params(my_params)
    my_params.permit(:address)
 	end

end

app/controllers/proofs_controller.rb
class ProofsController < ApplicationController
	def create
		@proof = Proof.new(proof_params)
		if @proof.save
			flash[:success] = "Photo uploaded at #{@proof.latitude}, #{@proof.longitude}"
		else
			flash[:warning] = @proof.errors.full_messages.each {|error| puts error}	
		end
      redirect_to root_url
	end

	private 

	def proof_params
		params.require(:proof).permit(:picture, :longitude, :latitude)
	end
end

app/controllers/ulocs_controller.rb
class UlocsController < ApplicationController
	def create
		@uloc = Uloc.new(uloc_params)
		if @uloc.save
			flash[:success] = "Location confirmed! Thank you!"
		else
			flash[:warning] = "An error occured with your location. Please try again"
		end
		redirect_to root_url
	end

	private	
		def uloc_params
	    params.require(:uloc).permit(:latitude, :longitude)
	 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/ulocs_helper.rb
module UlocsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geotagging</title>
  <%= include_gon %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css" />

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet-geocoder-mapzen/1.4.0/leaflet-geocoder-mapzen.css">
<link rel="stylesheet" href="https://unpkg.com/lrm-mapzen/dist/leaflet.routing.mapzen.css">

<script src="https://mapzen.com/tangram/0.7.0/tangram.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-routing-machine/3.0.0/leaflet-routing-machine.min.js"></script>
<script src="https://unpkg.com/lrm-mapzen/dist/lrm-mapzen.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-geocoder-mapzen/1.4.0/leaflet-geocoder-mapzen.js"></script>




  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |message_type, message| %>
        
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %> 

</div>
<%= yield %>

</body>
</html>

app/views/maps/_photo_form.html.erb
 <div class="col-lg-12 text-center">
                    <p><%= form_for(@proof, html: {multipart: true}) do |f|%>
                        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', required: 'required' %>                    
                        <%= f.submit "Add to map", class: "btn btn-lg btn-outline"%>
                        <% end %></p>
</div>

app/views/maps/_photo_map.html.erb
  
  <div id="photo-map" style="width: 100%; height: 400px">
     </div>
      <script>
     // set default view 
      if (gon.exif.length == 0){
       var map = L.map('photo-map').setView([16.826,96.1551], 13);
      }
      else{
        var last_photo = gon.exif[gon.exif.length -1]
        var map = L.map('photo-map').setView([last_photo[0], last_photo[1]], 14);
        }   

    L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    for (i=0; i<gon.exif.length; i++){
      L.marker([gon.exif[i][0],gon.exif[i][1]]).bindPopup("<p>"+gon.exif[i][2]+"</p><img src="+gon.exif[i][3]+">").addTo(map);
    }
    map.scrollWheelZoom.disable();

    </script>

app/views/maps/_route_form.html.erb
                <div class="col-lg-12 text-center">

Enter up to 5 cities to calculate the optimal route.
<%= form_tag packages_path, method: 'post' do %>
	<% @route.each do |package| %>
		<%= fields_for 'packages[]', package do |p| %>
		<% x = 1 %>
		<p>
			<%= p.text_field :address, style: "color:black", placeholder: "City" %>
		</p>
		<% x += 1 %>
		<% end %>
	<% end %>
	<%= submit_tag %>
<% end %>
<p> </p>
</div>

app/views/maps/_route_map.html.erb
<button onclick="getLocation()">Locate me</button>

<p id="demo"></p>

<script>
var x = document.getElementById("demo");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
    x.innerHTML = "Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude;


    var map = L.map('route-map').setView([position.coords.latitude,position.coords.longitude], 13);
L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

var marker = L.marker([position.coords.latitude,position.coords.longitude]).addTo(map);
marker.bindPopup("You are (probably) here!").openPopup();

L.Routing.control({
  waypoints: 
    <%= @map_route.each {|ad| puts "L.latLng(#{ad}),"}%>,

  router: L.Routing.mapzen('valhalla-3nES4Fs', {costing:'auto'}),
  formatter: new L.Routing.mapzenFormatter(),
  summaryTemplate:'<div class="start">{name}</div><div class="info {costing}">{distance}, {time}</div>',
  addWaypoints: false,
  show: false,
  fitSelectedRoutes: false
}).addTo(map); 
var geocoder = L.control.geocoder('search-jox3rEQ').addTo(map);


map.scrollWheelZoom.disable();
}
  </script>

app/views/maps/home.html.erb
 <div class="col-lg-1 col-centered">
  <h1>Geotracking </h1>
</div>

  <div id="route-map" style = "height: 450px;"></div>
  <%= render 'route_map' %>

    <section class="success" id="about">
        <div class="container">
            <div class="row">
              <% if @oo.count > 0 %>
              <%= "Showing route for" %>
              <%= @oo.each {|loc| puts loc[0]} %>
              <% else %> 
              <%= "No routes in the database" %>
              <% end %>

                <div class="col-lg-12 text-center">
                    <h2>Try it</h2>
                    <hr>
                </div>
            </div>
<p>Click the button to get your coordinates.</p>


        <%= render 'route_form' %>
        </div>
<%= render 'photo_map' %>
<%= render 'photo_form' %>            
<p> </p>

<!--new map
add js code for onclick
make marker onclick
make form (visible first)
link js onclick to form
implement form logic !-->

<div id="geolocate-map" style="width: 100%; height: 400px"></div>


 <script>

  // initialize the map
var map = L.map('geolocate-map').setView([16.82134316151232,96.14702224731445], 14);

  // load a tile layer
  // L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
  //     attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  //   }).addTo(map);
L.tileLayer('https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZGF2ZGF2IiwiYSI6ImNpcTd1eGdiZTAwcmNmaGtrM2lneGtzdHoifQ.vLPjuA4qqw_5ELT3Xc4nWQ').addTo(map);


var marker;

map.on('click', function(e) {
  if(typeof(marker) === 'undefined') {
    marker = new L.marker(e.latlng).bindPopup("find me here").addTo(map);
  }
  else
  {
    marker.setLatLng(e.latlng)
  }
  ulong.value = e.latlng.lng
  ulat.value = e.latlng.lat
});

map.scrollWheelZoom.disable();
</script>

 <div class="col-lg-12 text-center">

 <p><%= form_for(@uloc) do |f|%>
    <%= f.text_field :latitude, id: "ulat", style: "color:black", placeholder: "lat" %>
    <%= f.text_field :longitude, id: "ulong", style: "color:black", placeholder: "long" %>                
    <%= f.submit "Add to map", class: "btn btn-lg btn-outline"%>
<% end %></p>

</div>


  </section>